# 이메일 인증 정보
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=hhsky1111@gmail.com
spring.mail.password=ucexcmgwtirpyytb
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.default-encoding=UTF-8
spring.mvc.view.prefix=/WEB-INF/views/
spring.mvc.view.suffix=.jsp
